version: "3"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
     - ./data:/var/lib/grafana
     - /var/lib/grafana/plugins
     - ./ssl:/etc/grafana/ssl
    ports:
     - 3000:3000
    environment:
      GF_SERVER_PROTOCOL: "https"
      GF_SERVER_CERT_FILE: "/etc/grafana/ssl/grafana.crt"
      GF_SERVER_CERT_KEY: "/etc/grafana/ssl/grafana.key"
      GF_LOG_LEVEL: "debug"

